#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-TagTemplate
version:      1.82
version_from: TagTemplate.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
